### ISSUE TITLE
windows meson pthread not found

### ISSUE THREAD

**Issue by williamtu** [smadaminov/ovs-dpdk-meson-issues#21] opened 2021-07-27 19:14 UTC
FAILED: lib/libofproto.a.p/classifier.c.obj
"clang" "-Ilib\libofproto.a.p" "-Ilib" "-I..\lib" "-I." "-I.." "-Iinclude\openflow" "-I..\include\openflow" "-Iinclude\openv
switch" "-I..\include\openvswitch" "-Iinclude" "-I..\include" "-Xclang" "-fcolor-diagnostics" "-pipe" "-D_FILE_OFFSET_BITS=6
4" "-Wall" "-Winvalid-pch" "-g" "-Werror" -MD -MQ lib/libofproto.a.p/classifier.c.obj -MF "lib\libofproto.a.p\classifier.c.o
bj.d" -o lib/libofproto.a.p/classifier.c.obj "-c" ../lib/classifier.c
In file included from ../lib/classifier.c:18:
In file included from ..\lib/classifier.h:301:
In file included from ..\lib/cmap.h:22:
In file included from ..\lib/ovs-rcu.h:161:
..\lib/ovs-atomic.h:315:10: fatal error: 'pthread.h' file not found
#include <pthread.h>

**Comment by smadaminov** [comment] 2021-09-23 19:36
was caused by not linking with posix pthreads library. Now meson requires to provide this flag so closing. added as a prerequisite in the readme

**Closed by smadaminov** 2021-09-23 19:36 UTC
